---
title: "Flux at Collar Transects"
author: "Chloe"
date: "Data from 7/16/2019 measurements"
output: html_document
---
```{r setup, include=FALSE} 

knitr::opts_chunk$set(echo = TRUE) 

# Plots and Analysis 

library(here) 

library(ggplot2) 
#install.packages("xlsx")
#library(xlsx)

library(tidyr) 

library(dplyr) 

library(wesanderson) 

library('knitr') 
library(ggpubr)
#install.packages("miscTools")
#install.packages("matrixStats")
#install.packages("ggpubr")
library(miscTools)
library(matrixStats)

#install.packages("grid")
library(grid)
#install.packages("gridExtra")
library(gridExtra)

``` 

 

## Plots and Analysis 

 

```{r readData2, echo=FALSE} 

#flux of synoptics  

 


eos2 <- read.csv(here("FieldData/EosFD/eos2_08142019.csv"))

eos2$Year <- paste0("20",eos2$Year) 

eos2$dateTime <- as.POSIXct(as.character(paste0(eos2$Month,"/",eos2$Day,"/",eos2$Year," ",eos2$Time)), format = "%m/%d/%Y%H:%M:%OS") 

eos2 <- eos2%>% 

  select(dateTime,Flux) 

colnames(eos2) <- c("DateTime","Flux_eos2") 

 

 

#eos2$Flux_eos2 <- as.numeric(eos2$Flux_eos2) 

eos2$Flux_eos2 <- as.numeric(as.character(eos2$Flux_eos2)) 

  

 

eos1 <- read.csv(here("FieldData/EosFD",paste0("eos1_08132019.1.csv"))) 

eos1$Year <- paste0("20",eos1$Year) 

eos1$dateTime <- as.POSIXct(as.character(paste0(eos1$Month,"/",eos1$Day,"/",eos1$Year," ",eos1$Time)), format = "%m/%d/%Y%H:%M:%OS") 

eos1 <- eos1%>% 

  select(dateTime,Flux,Temperature..C.,CO2.Soil..ppm., 

         CO2.Soil.STD..ppm.,CO2.ATM..ppm.,CO2.ATM.STD..ppm.,Mode) 

colnames(eos1) <- c("DateTime","Flux_eos1","Temp_C_eos1","CO2_Soil_ppm_eos1","CO2_Soil_STD_ppm_eos1","CO2_ATM_ppm_eos1","CO2_ATM_STD_ppm_eos1","Mode") 

 

syn1 <- eos2[3581:3584,] 


syn5 <- eos2[3586:3589,] 

syn8 <- eos2[3591:3594,] 

syn11 <- eos2[3597:3600,] 

syn14 <- eos2[3604:3607,] 

 

waterfall <- eos1[1229:1232,] 

syn20 <- eos1[1234:1237,] 

syn23 <- eos1[1239:1242,] 

syn29 <- eos1[1245:1248,] 

syn35 <- eos1[1250:1252,] 

 

``` 


Average Flux of Each Site 

```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12} 

syn1avg <- mean(syn1$Flux_eos2) 

syn5avg <- mean(syn5$Flux_eos2) 

syn8avg <- mean(syn8$Flux_eos2) 

syn11avg <- mean(syn11$Flux_eos2) 

syn14avg <- mean(syn14$Flux_eos2) 

waterfallavg <- mean(waterfall$Flux_eos1) 

syn20avg <- mean(syn20$Flux_eos1) 

syn23avg <- mean(syn23$Flux_eos1) 

syn29avg <- mean(syn29$Flux_eos1) 

syn35avg <- mean(syn35$Flux_eos1) 

 

syn1sd <- sd(syn1$Flux_eos2) 

syn5sd <- sd(syn5$Flux_eos2) 

syn8sd <- sd(syn8$Flux_eos2) 

syn11sd <- sd(syn11$Flux_eos2) 

syn14sd <- sd(syn14$Flux_eos2) 

waterfallsd <- sd(waterfall$Flux_eos1) 

syn20sd <- sd(syn20$Flux_eos1) 

syn23sd <- sd(syn23$Flux_eos1) 

syn29sd <- sd(syn29$Flux_eos1) 

syn35sd <- sd(syn35$Flux_eos1) 

 

a <- data.frame(AverageFlux = c(syn35avg, syn29avg, syn23avg, syn20avg, waterfallavg, syn14avg, syn11avg, syn8avg, syn5avg, syn1avg)) 

rownames(a) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 

 
 

sd <- data.frame(StdDev= 

c(syn35sd, syn29sd, syn23sd, syn20sd, waterfallsd, syn14sd, syn11sd, syn8sd, syn5sd, syn1sd)) 

rownames(sd) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 


asyn08122019 <- a
ssyn08122019 <- sd
 

a <- cbind(a,sd) 

 
 

dis35 <- 0 

dis29 <- 37.4 

dis23 <- 75.9 

dis20 <- 94.1 

waterfalldis <- 107 

dis14 <- 143.7 

dis11 <- 169.9 

dis8 <- 194.9 

dis5 <- 217.6 

dis1<- 245.2 

dis <- data.frame(Distance = c(dis35, dis29, dis23, dis20, waterfalldis, dis14, dis11, dis8, dis5, dis1)) 

rownames(dis) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 


 

c <- cbind(a,dis) 

 

 

displot12 <- ggplot(c)+ 

 geom_errorbar(aes(x= Distance,y= AverageFlux, ymin= AverageFlux - StdDev, ymax= AverageFlux + StdDev), width=0.2, size=1, color="#009e73") +   

  geom_point(aes(x= Distance, y= AverageFlux), color = "#009e73", size = 3) + labs(x = "Synoptic Site Distance from Peatland (m) (8-12-2019)", y=expression(bold(CO["2"]~Evasion~'[umol'/~m^2~s~']')))

#displot12

 

 

``` 

```{r readDatas, echo=FALSE}
#flux of synoptics 

date<- "08012019"



eos2 <- read.csv(here("FieldData/EosFD",paste0("eos2_08142019.csv")))
eos2$Year <- paste0("20",eos2$Year)
eos2$dateTime <- as.POSIXct(as.character(paste0(eos2$Month,"/",eos2$Day,"/",eos2$Year," ",eos2$Time)), format = "%m/%d/%Y%H:%M:%OS")
eos2 <- eos2%>%
  select(dateTime,Flux)
colnames(eos2) <- c("DateTime","Flux_eos2")


#eos2$Flux_eos2 <- as.numeric(eos2$Flux_eos2)
eos2$Flux_eos2 <- as.numeric(as.character(eos2$Flux_eos2))
 

eos1 <- read.csv(here("FieldData/EosFD",paste0("eos1_08132019.1.csv")))
eos1$Year <- paste0("20",eos1$Year)
eos1$dateTime <- as.POSIXct(as.character(paste0(eos1$Month,"/",eos1$Day,"/",eos1$Year," ",eos1$Time)), format = "%m/%d/%Y%H:%M:%OS")
eos1 <- eos1%>%
  select(dateTime,Flux,Temperature..C.,CO2.Soil..ppm.,
         CO2.Soil.STD..ppm.,CO2.ATM..ppm.,CO2.ATM.STD..ppm.,Mode)
colnames(eos1) <- c("DateTime","Flux_eos1","Temp_C_eos1","CO2_Soil_ppm_eos1","CO2_Soil_STD_ppm_eos1","CO2_ATM_ppm_eos1","CO2_ATM_STD_ppm_eos1","Mode")


syn1 <- eos1[546:549,]
syn5 <- eos1[551:554,]
syn8 <- eos1[556:559,]
syn11 <- eos1[561:564,]
syn14 <- eos1[567:570,]
waterfall <- eos2[3041:3044,]
syn20 <- eos2[3047:3050,]
syn23 <- eos2[3052:3055,]
syn29 <- eos2[3058:3061,]
syn35 <- eos2[3064:3067,]

```


Average Flux of Each Site
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}
syn1avg <- mean(syn1$Flux_eos1)
syn5avg <- mean(syn5$Flux_eos1)
syn8avg <- mean(syn8$Flux_eos1)
syn11avg <- mean(syn11$Flux_eos1)
syn14avg <- mean(syn14$Flux_eos1)
waterfallavg <- mean(waterfall$Flux_eos2)
syn20avg <- mean(syn20$Flux_eos2)
syn23avg <- mean(syn23$Flux_eos2)
syn29avg <- mean(syn29$Flux_eos2)
syn35avg <- mean(syn35$Flux_eos2)

syn1sd <- sd(syn1$Flux_eos1)
syn5sd <- sd(syn5$Flux_eos1)
syn8sd <- sd(syn8$Flux_eos1)
syn11sd <- sd(syn11$Flux_eos1)
syn14sd <- sd(syn14$Flux_eos1)
waterfallsd <- sd(waterfall$Flux_eos2)
syn20sd <- sd(syn20$Flux_eos2)
syn23sd <- sd(syn23$Flux_eos2)
syn29sd <- sd(syn29$Flux_eos2)
syn35sd <- sd(syn35$Flux_eos2)
a <- data.frame(AverageFlux = c(syn35avg, syn29avg, syn23avg, syn20avg, waterfallavg, syn14avg, syn11avg, syn8avg, syn5avg, syn1avg)) 

rownames(a) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 

 

sd <- data.frame(StdDev= 

c(syn35sd, syn29sd, syn23sd, syn20sd, waterfallsd, syn14sd, syn11sd, syn8sd, syn5sd, syn1sd)) 

rownames(sd) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 

asyn08062019 <- a
ssyn08062019 <- sd

a <- cbind(a,sd) 

 


 

dis35 <- 0 

dis29 <- 37.4 

dis23 <- 75.9 

dis20 <- 94.1 

waterfalldis <- 107 

dis14 <- 143.7 

dis11 <- 169.9 

dis8 <- 194.9 

dis5 <- 217.6 

dis1<- 245.2 

dis <- data.frame(Distance = c(dis35, dis29, dis23, dis20, waterfalldis, dis14, dis11, dis8, dis5, dis1)) 

rownames(dis) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 



c <- cbind(a,dis) 

avgplot <- ggplot(c) +
  geom_point(aes(x= Distance, y= AverageFlux), color = "#d55e00", size = 3)   +
   geom_errorbar(aes(x= Distance,y= AverageFlux, ymin= AverageFlux - StdDev, ymax= AverageFlux + StdDev), width=0.2, size=1, color="#d55e00") +   
labs(x = "Synoptic Site Distance from Peatland (m) (8-06-2019)", y=expression(bold(CO["2"]~Evasion~'[umol'/~m^2~s~']')))
avgplot

combined1 <- displot12 + 
  geom_point(data = c, aes(x= Distance, y= AverageFlux), color = "#d55e00", size = 3) +
   geom_errorbar(data = c, aes(x= Distance,y= AverageFlux, ymin= AverageFlux - StdDev, ymax= AverageFlux + StdDev), width=0.2, size=1, color="#d55e00") +   labs(x = "Synoptic Site Distance from Peatland (m)", y=expression(bold(CO["2"]~Evasion~'[umol'/~m^2~s~']')))

#combined1


``` 
combine
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}
displot <- ggarrange(displot12, avgplot)
#displot

``` 

```{r readDatap, echo=FALSE}
date<- "08012019"




eos2 <- read.csv(here("FieldData/EosFD",paste0("eos2_",date,".csv")))
eos2$Year <- paste0("20",eos2$Year)
eos2$dateTime <- as.POSIXct(as.character(paste0(eos2$Month,"/",eos2$Day,"/",eos2$Year," ",eos2$Time)), format = "%m/%d/%Y%H:%M:%OS")
eos2 <- eos2%>%
  select(dateTime,Flux,Temperature..C.,CO2.Soil..ppm..,
         CO2.Soil.STD..ppm.,CO2.ATM..ppm.,CO2.ATM.STD..ppm.,Mode)
colnames(eos2) <- c("DateTime","Flux_eos2","Temp_C_eos2","CO2_Soil_ppm_eos2","CO2_Soil_STD_ppm_eos2","CO2_ATM_ppm_eos2","CO2_ATM_STD_ppm_eos2","Mode")

eos1 <- read.csv(here("FieldData/EosFD",paste0("eos1_FIX_07312019.csv")))
#eos1$Year <- paste0("20",eos1$Year)
#eos1$dateTime <- as.POSIXct(as.character(paste0(eos1$Month,"/",eos1$Day,"/",eos1$Year," ",eos1$Time)), format = "%m/%d/%Y %H:%M:%OS")
eos1 <- eos1%>%
  select(DateTime,Flux_1,Temp_C_1,CO2_Soil_1,
        CO2_Soil_STD_1,CO2_ATM_1,CO2_ATM_STD_1,Mode_1)
colnames(eos1) <- c("DateTime","Flux_eos1","Temp_C_eos1","CO2_Soil_ppm_eos1","CO2_Soil_STD_ppm_eos1","CO2_ATM_ppm_eos1","CO2_ATM_STD_ppm_eos1","Mode")



syn1 <- eos2[2177:2180,]
syn5 <- eos2[2183:2186,]
syn8 <- eos2[2188:2191,]
syn11 <- eos2[2193:2196,]
syn14 <- eos2[2200:2203,]
waterfall <- eos1[2534:2537,]
syn20 <- eos1[2540:2543,]
syn23 <- eos1[2546:2549,]
syn29 <- eos1[2552:2555,]
syn35 <- eos1[2557:2560,]

```

Average Flux of Each Site 7-31-2019
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}
syn1avg <- mean(syn1$Flux_eos2)
syn5avg <- mean(syn5$Flux_eos2)
syn8avg <- mean(syn8$Flux_eos2)
syn11avg <- mean(syn11$Flux_eos2)
syn14avg <- mean(syn14$Flux_eos2)
waterfallavg <- mean(waterfall$Flux_eos1)
syn20avg <- mean(syn20$Flux_eos1)
syn23avg <- mean(syn23$Flux_eos1)
syn29avg <- mean(syn29$Flux_eos1)
syn35avg <- mean(syn35$Flux_eos1)

syn1sd <- sd(syn1$Flux_eos2)
syn5sd <- sd(syn5$Flux_eos2)
syn8sd <- sd(syn8$Flux_eos2)
syn11sd <- sd(syn11$Flux_eos2)
syn14sd <- sd(syn14$Flux_eos2)
waterfallsd <- sd(waterfall$Flux_eos1)
syn20sd <- sd(syn20$Flux_eos1)
syn23sd <- sd(syn23$Flux_eos1)
syn29sd <- sd(syn29$Flux_eos1)
syn35sd <- sd(syn35$Flux_eos1)


a <- data.frame(AverageFlux = c(syn35avg, syn29avg, syn23avg, syn20avg, waterfallavg, syn14avg, syn11avg, syn8avg, syn5avg, syn1avg)) 

rownames(a) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 

sd <- data.frame(StdDev= 

c(syn35sd, syn29sd, syn23sd, syn20sd, waterfallsd, syn14sd, syn11sd, syn8sd, syn5sd, syn1sd)) 

rownames(sd) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 


asyn07312019 <- a
ssyn07312019 <- sd

a <- cbind(a,sd) 

 

dis35 <- 0 

dis29 <- 37.4 

dis23 <- 75.9 

dis20 <- 94.1 

waterfalldis <- 107 

dis14 <- 143.7 

dis11 <- 169.9 

dis8 <- 194.9 

dis5 <- 217.6 

dis1<- 245.2 

dis <- data.frame(Distance = c(dis35, dis29, dis23, dis20, waterfalldis, dis14, dis11, dis8, dis5, dis1)) 

rownames(dis) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 



c <- cbind(a,dis) 

 

displot31 <- ggplot(c) +

 geom_errorbar(aes(x= Distance,y= AverageFlux, ymin= AverageFlux - StdDev, ymax= AverageFlux + StdDev), width=0.2, size=1, color="blue") +   

  geom_point(aes(x= Distance, y= AverageFlux), color = "blue", size = 3) + labs(x = "Synoptic Site Distance from Peatland (07-31-2019) (m)", y=expression(bold(CO["2"]~Evasion~'[umol'/~m^2~s~']')))

#displot31
 

combined2 <- combined1 + 

 geom_errorbar(data = c, aes(x= Distance,y= AverageFlux, ymin= AverageFlux - StdDev, ymax= AverageFlux + StdDev), width=0.2, size=1, color="blue") +   

  geom_point(data = c, aes(x= Distance, y= AverageFlux), color = "blue", size = 3) + labs(x = "Synoptic Site Distance from Peatland (m)", y=expression(bold(CO["2"]~Evasion~'[umol'/~m^2~s~']')))

#combined2


``` 

```{r readData, echo=FALSE}
#flux of synoptics 

date<- "07292019"


# eos2 data
eos2 <- read.csv(here("FieldData/EosFD",paste0("eos2_",date,".csv")))
eos2$Year <- paste0("20",eos2$Year)
eos2$dateTime <- as.POSIXct(as.character(paste0(eos2$Month,"/",eos2$Day,"/",eos2$Year," ",eos2$Time)), format = "%m/%d/%Y %H:%M:%OS")
eos2 <- eos2%>%
  select(dateTime,Flux,Temperature..C.,CO2.Soil..ppm..,
         CO2.Soil.STD..ppm.,CO2.ATM..ppm.,CO2.ATM.STD..ppm.,Mode)
colnames(eos2) <- c("DateTime","Flux_eos2","Temp_C_eos2","CO2_Soil_ppm_eos2","CO2_Soil_STD_ppm_eos2",
                    "CO2_ATM_ppm_eos2","CO2_ATM_STD_ppm_eos2","Mode")


# Subset data so only records at 5 minute intervals are retained
#sub.1 <- subset(eos2, format(DateTime,'%OS')=='00')
#sub.2 <- subset(sub.1, format(DateTime,'%M')%in% c("00","05","10","15","20","25","30","35","40","45","50","55","60"))

# eos1 data
eos1 <- read.csv(here("FieldData/EosFD","eos1_FIX_07312019.csv"))
#eos1$DateTime <- as.POSIXct(eos1$DateTime, format = "%m/%d/%Y %H:%M:%OS")
#eos2$dateTime <- as.POSIXct(as.character((eos2$Month,"/",eos2$Day,"/",eos2$Year," ",eos2$Time)), format = "%m/%d/%Y %H:%M:%OS")
# Subset data so only records at 5 minute intervals are retained
#sub.11 <- subset(eos1, format(DateTime,'%OS')=='00')
#sub.22 <- subset(sub.11, format(DateTime,'%M')%in% c("00","05","10","15","20","25","30","35","40","45","50","55","60"))


syn1 <- eos1[1854:1857,]
syn5 <- eos1[1860:1863,]
syn10 <- eos1[1871:1873,]
syn14 <- eos1[1879:1882,]
waterfall <- eos2[1158:1161,]
syn23 <- eos2[1169:1172,]
syn29 <- eos2[1175:1178,]
syn35 <- eos2[1180:1183,]

```

Average Flux of Each Site
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}
syn1avg <- mean(syn1$Flux_1)
syn5avg <- mean(syn5$Flux_1)
syn10avg <- mean(syn10$Flux_1)
syn14avg <- mean(syn14$Flux_1)
waterfallavg <- mean(waterfall$Flux_eos2)
syn23avg <- mean(syn23$Flux_eos2)
syn29avg <- mean(syn29$Flux_eos2)
syn35avg <- mean(syn35$Flux_eos2)

syn1sd <- sd(syn1$Flux_1)
syn5sd <- sd(syn5$Flux_1)
syn10sd<- sd(syn10$Flux_1)
syn14sd <- sd(syn14$Flux_1)
waterfallsd <- sd(waterfall$Flux_eos2)
syn23sd <- sd(syn23$Flux_eos2)
syn29sd <- sd(syn29$Flux_eos2)
syn35sd <- sd(syn35$Flux_eos2)

a <- data.frame(AverageFlux = c(syn35avg, syn29avg, syn23avg, waterfallavg, syn14avg, syn10avg, syn5avg, syn1avg)) 

rownames(a) <- c("syn35", "syn29", "syn23", "waterfall", "syn14", "syn10", "syn 5", "syn1") 


sd <- data.frame(StdDev= 

c(syn35sd, syn29sd, syn23sd,  waterfallsd, syn14sd, syn10sd, syn5sd, syn1sd)) 

rownames(sd) <- c("syn35", "syn29", "syn23", "waterfall", "syn14", "syn10", "syn 5", "syn1") 


asyn07252019 <- a
ssyn07252019 <- sd

a <- cbind(a,sd) 


 

dis35 <- 0 

dis29 <- 37.4 

dis23 <- 75.9 

waterfalldis <- 107 
dis14 <- 143.7 

dis10 <- 178.7

dis5 <- 217.6 

dis1<- 245.2 

dis <- data.frame(Distance = c(dis35, dis29, dis23, waterfalldis, dis14, dis10, dis5, dis1)) 

rownames(dis) <- c("syn35", "syn29", "syn23", "waterfall", "syn14", "syn10", "syn 5", "syn1") 


c <- cbind(a,dis) 

 

 

displot25 <- ggplot(c)+ 

 geom_errorbar(aes(x= Distance,y= AverageFlux, ymin= AverageFlux - StdDev, ymax= AverageFlux + StdDev), width=0.2, size=1, color="#56B4E9") +   

  geom_point(aes(x= Distance, y= AverageFlux), color = "#56B4E9", size = 3) +   labs(x = "Synoptic Site Distance from Peatland (m) (7-25-3029)", y=expression(bold(CO["2"]~Evasion~'[umol'/~m^2~s~']'))) 




combined3 <- combined2 + 

 geom_errorbar(data = c, aes(x= Distance,y= AverageFlux, ymin= AverageFlux - StdDev, ymax= AverageFlux + StdDev), width=0.2, size=1, color="#56B4E9") +   

  geom_point(data = c, aes(x= Distance, y= AverageFlux), color = "#56B4E9", size = 3) + labs(x = "Synoptic Site Distance from Peatland (m)", y=expression(bold(CO["2"]~Evasion~'[umol'/~m^2~s~']')))

#combined3

 

``` 

```{r readDatfa, echo=FALSE}
#flux of synoptics 

date<- "07182019"


# eos1 data
eos2 <- read.csv(here("FieldData/EosFD",paste0("eos2_",date,".csv")))
eos2$Year <- paste0("20",eos2$Year)
eos2$dateTime <- as.POSIXct(as.character(paste0(eos2$Month,"/",eos2$Day,"/",eos2$Year," ",eos2$Time)), format = "%m/%d/%Y %H:%M:%OS")
eos2 <- eos2%>%
  select(dateTime,Flux,Temperature..C.,CO2.Soil..ppm.,
         CO2.Soil.STD..ppm.,CO2.ATM..ppm.,CO2.ATM.STD..ppm.,Mode)
colnames(eos2) <- c("DateTime","Flux_eos2","Temp_C_eos2","CO2_Soil_ppm_eos2","CO2_Soil_STD_ppm_eos2",
                    "CO2_ATM_ppm_eos2","CO2_ATM_STD_ppm_eos2","Mode")


# Subset data so only records at 5 minute intervals are retained
sub.1 <- subset(eos2, format(DateTime,'%OS')=='00')
sub.2 <- subset(sub.1, format(DateTime,'%M')%in% c("00","05","10","15","20","25","30","35","40","45","50","55","60"))
sub.2 <- sub.2[500:565,]
rownames(sub.2) <- NULL
#this above code is good

syn1 <- sub.2[2:6,]
syn5 <- sub.2[8:11,]
syn8 <- sub.2[13:17,]
syn8 <- syn8[which(syn8$Flux_eos2 > 0), ]
syn11 <- sub.2[19:22,]
syn14 <- sub.2[27:30,]
waterfall <- sub.2[36:39,]
syn20 <- sub.2[44:47,]
syn23 <- sub.2[50:53,]
syn29 <- sub.2[57:60,]
syn35 <- sub.2[63:66,]

```
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}
syn1avg <- mean(syn1$Flux_eos2)
syn5avg <- mean(syn5$Flux_eos2)
syn8avg <- mean(syn8$Flux_eos2)
syn11avg <- mean(syn11$Flux_eos2)
syn14avg <- mean(syn14$Flux_eos2)
waterfallavg <- mean(waterfall$Flux_eos2)
syn20avg <- mean(syn20$Flux_eos2)
syn23avg <- mean(syn23$Flux_eos2)
syn29avg <- mean(syn29$Flux_eos2)
syn35avg <- mean(syn35$Flux_eos2)

syn1sd <- sd(syn1$Flux_eos2)
syn5sd <- sd(syn5$Flux_eos2)
syn8sd <- sd(syn8$Flux_eos2)
syn11sd <- sd(syn11$Flux_eos2)
syn14sd <- sd(syn14$Flux_eos2)
waterfallsd <- sd(waterfall$Flux_eos2)
syn20sd <- sd(syn20$Flux_eos2)
syn23sd <- sd(syn23$Flux_eos2)
syn29sd <- sd(syn29$Flux_eos2)
syn35sd <- sd(syn35$Flux_eos2)

a <- data.frame(AverageFlux = c(syn35avg, syn29avg, syn23avg, syn20avg, waterfallavg, syn14avg, syn11avg, syn8avg, syn5avg, syn1avg)) 

rownames(a) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 


 

sd <- data.frame(StdDev= 

c(syn35sd, syn29sd, syn23sd, syn20sd, waterfallsd, syn14sd, syn11sd, syn8sd, syn5sd, syn1sd)) 

rownames(sd) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 

asyn07182019 <- a
ssyn07182019 <- sd
 

a <- cbind(a,sd) 

 

 

dis35 <- 0 

dis29 <- 37.4 

dis23 <- 75.9 

dis20 <- 94.1 

waterfalldis <- 107 

dis14 <- 143.7 

dis11 <- 169.9 

dis8 <- 194.9 

dis5 <- 217.6 

dis1<- 245.2 

dis <- data.frame(Distance = c(dis35, dis29, dis23, dis20, waterfalldis, dis14, dis11, dis8, dis5, dis1)) 

rownames(dis) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 

#kable(dis, format = "markdown", row.names = TRUE) 

 

c <- cbind(a,dis) 

 

displot18 <- ggplot(c)+ 

 geom_errorbar(aes(x= Distance,y= AverageFlux, ymin= AverageFlux - StdDev, ymax= AverageFlux + StdDev), width=0.2, size=1, color="#cc79a7") +   

  geom_point(aes(x= Distance, y= AverageFlux), color = "#cc79a7", size = 3) +   labs(x = "Synoptic Site Distance from Peatland (m) (7-18-3029)", y= expression(bold(Flux~('umol'/~m^2~s))) )




combined4 <- combined3 + 

 geom_errorbar(data = c, aes(x= Distance,y= AverageFlux, ymin= AverageFlux - StdDev, ymax= AverageFlux + StdDev), width=0.2, size=1, color="#cc79a7") +   

  geom_point(data = c, aes(x= Distance, y= AverageFlux), color = "#cc79a7", size = 3) + labs(x = "Synoptic Site Distance from Peatland (m)", y=expression(bold(CO["2"]~Evasion~'[umol'/~m^2~s~']'))) + theme_bw(base_size = 18)

combined4 <- combined4 +   
labs(x = "Distance from Peatland [m]", y=expression(bold(CO["2"]~Evasion~'[umol'/~m^2~s~']'))) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=20,face="bold"),
        axis.title.y = element_text(size = 20))+
  theme(panel.border = element_rect(fill=NA, colour = "black", size=1.5)) + ylim(0,12)
combined4


combined4

library(tidyverse)
library(here)
library(dplyr)
library(ggplot2)
library(plotly)
Synoptics <- read.csv(here("FieldData/Vaisala/Synoptics2.csv"))
plot <- ggplot(Synoptics) +
  geom_point(aes(x= Distance, y= Syn1_071819, color= "0.0085"), size = 3) +
  geom_point(aes(x= Distance, y= Syn2_072519, color= "0.0228"), size = 3) +
  geom_point(aes(x= Distance, y= Syn3_072919, color= "0.0071"), size = 3) +
  geom_point(aes(x= Distance, y= Syn4_073119, color= "0.0076"), size = 3) +
  geom_point(aes(x= Distance, y= Syn5_080619, color= "0.0042"), size = 3) +
  geom_point(aes(x= Distance, y= Syn6_081219, color= "0.0025"), size = 3) +
  scale_color_manual(values=c("#009e73","#d55e00","#FDE725FF","blue","#cc79a7","#56B4E9")) +
  labs(x = "Distance from Peatland [m]", y= expression(bold(pCO["2"]~"[ppm]")), 
       color= expression(bold(Discharge~'['~m^3/s~']'))) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=20,face="bold"),
        axis.title.y = element_text(size = 20))+
  theme(legend.position= c(0.8, 0.65),
        legend.title = element_text(size = 14,face="bold"),
        legend.text = element_text(size = 12)) +
  theme(legend.background = element_rect(colour = 'black', fill = 'white', linetype='solid')) +
  theme(panel.border = element_rect(fill=NA, colour = "black", size=1.5))

plot
combined4

both <- ggarrange(plot, combined4)
both
``` 